language: generic
sudo: required

services:
  - docker
  
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud/stretch .
  
after_success:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push r2cloud/stretch;
    fi