language: generic
sudo: required

services:
  - docker
  
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud/stretch .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push r2cloud/stretch;
    fi